[project]
name = "rel-rag"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai (>=2.9.0,<3.0.0)",
    "google-cloud-bigquery (>=3.42.0,<4.0.0)"
]

[tool.poetry]
packages = [{include = "rel_rag", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
